// Builds js/data/geo.js: a coastline outline for the East of England map and a
// postcode-district / town gazetteer, so the site can geocode and draw its map
// without calling any external service.
//
// Inputs (downloaded separately, see README):
//   land-10m.json  - Natural Earth land, TopoJSON (npm world-atlas@2.0.2)
//   postcodes.csv  - UK outward-code centroids (github.com/Gibbs/uk-postcodes,
//                    derived from OS Code-Point Open, Open Government Licence)
//   GB.txt         - GeoNames GB place names (download.geonames.org/export/dump/GB.zip, CC BY 4.0)
// Usage: node tools/build_geodata.js <land-10m.json> <postcodes.csv> <GB.txt>
const fs = require('fs');
const path = require('path');

const [landPath, csvPath, namesPath] = process.argv.slice(2);
const HOME = { lat: 52.2053, lng: 0.1218 }; // Cambridge
const BOX = { minLng: -2.6, maxLng: 2.1, minLat: 50.9, maxLat: 53.6 };

// --- coastline ---------------------------------------------------------------
const topo = JSON.parse(fs.readFileSync(landPath, 'utf8'));
const { scale, translate } = topo.transform;
const arcs = topo.arcs.map(arc => {
  let x = 0, y = 0;
  return arc.map(([dx, dy]) => {
    x += dx; y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
  });
});
function arcPoints(i) {
  return i >= 0 ? arcs[i] : arcs[~i].slice().reverse();
}
const rings = [];
function addPolygon(poly) {
  for (const ring of poly) {
    const pts = [];
    for (const i of ring) pts.push(...arcPoints(i));
    rings.push(pts);
  }
}
for (const geom of topo.objects.land.geometries) {
  if (geom.type === 'Polygon') addPolygon(geom.arcs);
  else if (geom.type === 'MultiPolygon') geom.arcs.forEach(addPolygon);
}
const clamp = (v, a, b) => Math.min(b, Math.max(a, v));
const PAD = 0.3;
const out = [];
for (const ring of rings) {
  const inBox = ring.some(([x, y]) => x > BOX.minLng && x < BOX.maxLng && y > BOX.minLat && y < BOX.maxLat);
  if (!inBox) continue;
  const simplified = [];
  let prev = null;
  for (const [x0, y0] of ring) {
    const x = +clamp(x0, BOX.minLng - PAD, BOX.maxLng + PAD).toFixed(3);
    const y = +clamp(y0, BOX.minLat - PAD, BOX.maxLat + PAD).toFixed(3);
    if (prev && Math.abs(prev[0] - x) < 0.008 && Math.abs(prev[1] - y) < 0.008) continue;
    simplified.push([x, y]);
    prev = [x, y];
  }
  if (simplified.length > 3) out.push(simplified);
}

// --- gazetteer -----------------------------------------------------------------
function miles(a, b) {
  const R = 3958.8, rad = Math.PI / 180;
  const dLat = (b.lat - a.lat) * rad, dLng = (b.lng - a.lng) * rad;
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(a.lat * rad) * Math.cos(b.lat * rad) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}
const lines = fs.readFileSync(csvPath, 'utf8').trim().split('\n').slice(1);
const outcodes = {};
for (const line of lines) {
  const [code, , , lat, lng] = line.split(',');
  if (!isFinite(+lat) || !isFinite(+lng) || (+lat === 0 && +lng === 0)) continue;
  outcodes[code] = [+(+lat).toFixed(4), +(+lng).toFixed(4)];
}
// Populated places (not neighbourhoods) within 110 miles; for repeated names
// keep the most populous, then the nearest.
const townOut = {};
const best = {};
for (const line of fs.readFileSync(namesPath, 'utf8').split('\n')) {
  const f = line.split('\t');
  if (f[6] !== 'P' || f[7] === 'PPLX' || f[7] === 'PPLH' || f[7] === 'PPLQ') continue;
  const p = { lat: +f[4], lng: +f[5] };
  const d = miles(HOME, p);
  if (d > 110) continue;
  const pop = +f[14] || 0;
  const name = f[1];
  const prev = best[name];
  if (!prev || pop > prev.pop || (pop === prev.pop && d < prev.d)) best[name] = { ...p, pop, d };
}
for (const [name, p] of Object.entries(best)) townOut[name] = p.pop ? [+p.lat.toFixed(3), +p.lng.toFixed(3), p.pop] : [+p.lat.toFixed(3), +p.lng.toFixed(3)];

const js = `// Generated by tools/build_geodata.js. Do not edit by hand.
// Coastline: Natural Earth (public domain). Postcode districts: OS Code-Point Open
// via github.com/Gibbs/uk-postcodes (Open Government Licence v3).
// Towns: GeoNames (CC BY 4.0), as [lat, lng, population].
window.MOTO_GEO = {
  box: ${JSON.stringify(BOX)},
  land: ${JSON.stringify(out)},
  outcodes: ${JSON.stringify(outcodes)},
  towns: ${JSON.stringify(townOut)}
};
`;
const dest = path.join(__dirname, '..', 'js', 'data', 'geo.js');
fs.writeFileSync(dest, js);
console.log(`rings=${out.length} points=${out.reduce((s, r) => s + r.length, 0)} outcodes=${Object.keys(outcodes).length} towns=${Object.keys(townOut).length} bytes=${js.length}`);
